### PR TITLE
Added taxonomy + term appending to ucf_degree_append_meta()

### LINKED ISSUE #7: Append taxonomy term objects to Degree $post objects
Need to add a function similar to ucf_degree_append_meta() that appends taxonomy term objects to a degree $post object.

Reference--Online-Theme's previous meta-appending function also appended the degree college term and program type term; lines 1126, 1132, and 1136 here all throw notices after updates to the rc-v2.0.0 branch to use the Degree CPT plugin's ucf_degree_append_meta() function instead.
https://github.com/UCF/Online-Theme/blob/rc-v2.0.0/migrate/shortcodes.php#L1123-L1137

### PR DESCRIPTION
**Pull request by cjg89**
Resolves #7.

### CODE REVIEW

**Comment by rjucf** [comment]
looks good

**Comment by keeeeeegan** [comment]
Looks good

**Comment by jmbarne3** [comment]
I think it would make more sense to have the ucf_degree_append_meta only append meta data related to the post and to have tax data appended by another function. The addition of the tax terms and related meta adds a bit of overhead to the request and splitting it up will give developers more options on how much data they want to retrieve for any given request.

**Comment by cjg89** [comment]
Yeah I had a hard time deciding whether or not to make it a separate function--I ended up lumping the logic into ucf_degree_append_meta() primarily to maintain the existing functionality of the append_degree_metadata() function in Online, and avoid having to potentially call two separate functions to add extra data to a $post object.  The code is merged into master but I've re-opened the issue and will try to look into this later.

**Pull request merged**
