### PR TITLE
Typeahead query

### PR DESCRIPTION
**Pull request by jmbarne3**
Added some custom filters for doing a very specific search for degrees. Whenever the `degree_search` param is present multiple additional tables will be joined, additional where clauses and then a group by statement added. This enhancement is meant to provide a more usable search api for the typeahead component.

### CODE REVIEW

**Comment by cjg89** [comment]
Looks good.

**Comment by rjucf** [comment]
good

**Comment by keeeeeegan** [comment]
Good

**Comment by jmbarne3** [comment]
Made some additional changes to this to make it a little less hacky and added some additional comments. Could I have everyone give one last look over?

**Comment by cjg89** [comment]
Updates look good to me.

**Pull request merged**
